<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>Briosa.Installer</AssemblyName>
    <ApplicationIcon>Assets/AppIcon/briosa.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Briosa.Installer.Core/Briosa.Installer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets/Brand/png/logos/*.png" />
    <Resource Include="Assets/Brand/fonts/Inter-Variable.ttf" />
    <Resource Include="Assets/AppIcon/briosa.ico" />
  </ItemGroup>
</Project>
